define([], function () {
    return [
        {
            code: "name",
            custom_field: false,
            default_code: "",
            disabled: false,
            element_type: 2,
            format: false,
            id: "10",
            id_name: "name",
            shown: true,
            sort: "name",
            sortable: true,
            sorted: "ASC",
            template: "name",
            template_params: null,
            title: "Название сделки",
            type_code: "text",
            width: 3.73
        },
        {
            code: "budget",
            custom_field: false,
            default_code: "",
            disabled: false,
            element_type: 2,
            format: false,
            id: "60",
            id_name: "budget",
            shown: true,
            sort: "budget",
            sortable: true,
            sorted: false,
            template: "budget",
            template_params: null,
            title: "Бюджет",
            type_code: "text",
            width: 2.49
        },
        {
            code: "main_contact",
            custom_field: false,
            default_code: "",
            disabled: false,
            element_type: 2,
            format: false,
            id: "20",
            id_name: "main_contact",
            shown: true,
            sort: "main_contact",
            sortable: false,
            sorted: false,
            template: "link",
            template_params: null,
            title: "Основной контакт",
            type_code: "text",
            width: 6.13
        },
        {
            code: "cf552815",
            custom_field: true,
            default_code: "numeric",
            disabled: false,
            element_type: 2,
            format: false,
            id: "552815",
            shown: true,
            sort: "cf552815",
            sortable: true,
            sorted: false,
            template: "text",
            template_params: null,
            title: "Остаток",
            type_code: "numeric",
            width: 2.44
        },
        {
            code: "status",
            custom_field: false,
            default_code: "",
            disabled: false,
            element_type: 2,
            format: false,
            id: "50",
            id_name: "status",
            shown: true,
            sort: "status",
            sortable: true,
            sorted: false,
            template: "status",
            template_params: null,
            title: "Этап сделки",
            type_code: "text",
            width: 3.64
        },
        {
            code: "cf552951",
            custom_field: true,
            default_code: "checkbox",
            disabled: false,
            element_type: 2,
            format: false,
            id: "552951",
            shown: true,
            sort: "cf552951",
            sortable: true,
            sorted: false,
            template: "checkbox",
            template_params: null,
            title: "Медкомиссия",
            type_code: "checkbox",
            width: 3.13
        }
    ]
});